### ISSUE TITLE
The new mlmodel

### ISSUE THREAD

**Issue by dfrumkin** [FilippoAleotti/mobilePydnet#10]
Hello!  Great work!  I have a few questions:
Is the new mlmodel the one trained using MiDaS outputs on 450K internet images?
What is its output?  Looks like an 8-bit image that would be scaled and shifted disparity map.  Is that right?  What if I want to get the original disparity map (or at least floats and not uint), is there an easy way to modify the mlmodel?

**Comment by FilippoAleotti** [comment]
Hi,
Yes, in the conversion the output type is set to imageType.colorSpace(“GRAYSCALE”), to visualize depth maps in the application as images. If you need float values you can use the json serialized tensorflow model available [here](https://github.com/FilippoAleotti/demo_live/blob/master/assets/js/pydnet.json)

**Comment by dfrumkin** [comment]
Great, thank you, Filippo!
