### ISSUE TITLE
what is the range you used for midas output

### ISSUE THREAD

**Issue by daisily727** [FilippoAleotti/mobilePydnet#17]
As midas output range is from 0 to a few thousand, I tried to use this output as supervision but found the loss cannot decrease at all. If I scale the output to 0 to 1, the training will converge to all zero output very quickly. Can I know what range you used in your training? thx

**Comment by FilippoAleotti** [comment]
Hi,
I used [0,255] range

**Comment by daisily727** [comment]
> Hi,
> I used [0,255] range

Thanks for your prompt response. One more question, in the gradient loss computation, did you use multi-scale (e.g. 4 scales in previous papers)?

**Comment by FilippoAleotti** [comment]
Hi, sorry for the delay. Predictions are upsampled to full resolution before loss computation, and about the gradient term yes, it takes relevant predictions (e.g. from scale 0,1 and 2) and apply a  weight to each one (lower the scale, lower the weight)
