### ISSUE TITLE
Dataset release

### ISSUE THREAD

**Issue by OwenHua666** [FilippoAleotti/mobilePydnet#18]
This is really amazing work with great real-life application potential. Will you provide more details about the training dataset?

**Comment by FilippoAleotti** [comment]
Hi, I didn’t notice that the link to the paper was missing here. You can find more details [here](https://arxiv.org/pdf/2006.05724.pdf)

**Comment by OwenHua666** [comment]
Thanks! Do you guys plan to release the WILD dataset? As you guys mentioned there are some selections from COCO and Open images.

**Comment by OwenHua666** [comment]
In the paper you mentioned above, it repoints back to this repo for more details.

**Comment by FilippoAleotti** [comment]
There is the full list [here](https://github.com/FilippoAleotti/mobilePydnet/blob/v2/single_inference/train_files.txt)

**Comment by OwenHua666** [comment]
Thanks!
