### ISSUE TITLE
How to collect training dataset

### ISSUE THREAD

**Issue by sfdn123** [FilippoAleotti/mobilePydnet#20]
Hi @FilippoAleotti 
I want to train this model myself.
I looked into Pydnet and monodepth and both used stereo images as training data 
Did you create the Depthmap in Midas and use it to create a stereo image?

**Comment by FilippoAleotti** [comment]
Hi,
No, we didn’t create a stereo pair, we just used the depth map as reference signal during the training of Pydnet.

**Comment by sfdn123** [comment]
i got it. Thanks for the reply!
