### ISSUE TITLE
How does mobilePydnet architecture differ from Pydnet architecture

### ISSUE THREAD

**Issue by zshn25** [FilippoAleotti/mobilePydnet#25]
You have mentioned in the paper that transposed convolutions have been replaced by upsampling and convolution blocks. What else has been changed?

**Comment by FilippoAleotti** [comment]
Hi, 
In the original pydnet, in each decoder we get the disparity by slicing the last feature map. Here we obtain disparities with a convolutional layer.

**Comment by zshn25** [comment]
Thank you. Could you tell me why these changes? Why replace transpose convolutions and why convolution layer for disparity at the end of decoder?

**Comment by FilippoAleotti** [comment]
About transposed, also for [this](https://distill.pub/2016/deconv-checkerboard/), while about disparity estimation, the number of parameters and time that slice allows to gain it’s quite limited, so I opted for these (minor) changes.

**Comment by zshn25** [comment]
Off topic, but I've implemented both Pydnet and the mobile version in Pytorch [here](https://github.com/zshn25/Pydnet-Pytorch) You can review if you have time and link it in the READMEs. Thanks!
