### ISSUE TITLE
Android Version

### ISSUE THREAD

**Issue by mad-lad1** [FilippoAleotti/mobilePydnet#36]
Hello, 

this is more of a request rather than an issue. Will you be open-sourcing the Android code anytime soon.

Thank you so much for this amazing work!

**Comment by rodrigoGA** [comment]
Hi, if you share the tensorflow lite model, I can help you on this.

**Comment by mad-lad1** [comment]
Hi!

I ended up switching to another solution. 
Thanks for your help!

I will close this issue now.

**Comment by rodrigoGA** [comment]
@mad-lad1   with tensorflow lite model?
Could you say the name of the project, to compare results with this one?
