### ISSUE TITLE
Unable to get same quality depthmap as in provided Android screenshots

### ISSUE THREAD

**Issue by iVoider** [FilippoAleotti/mobilePydnet#5]
Hello!
I'm testing android variant, however camera and single loaded bitmap don't produce same depthmap color difference. I've tried both networks(mobilenet and tf lite) with different scale parameters.
So is it possible to get same results(perfomance doesn't matter)?

![1](https://user-images.githubusercontent.com/13479402/74736216-46b92480-5263-11ea-9aa0-da775a3a51c5.png)
![2](https://user-images.githubusercontent.com/13479402/74736222-4b7dd880-5263-11ea-9c1e-5b3a48fc34b8.png)

**Comment by FilippoAleotti** [comment]
Hi,
try to change this setting https://github.com/FilippoAleotti/mobilePydnet/blob/ddd472fca53c869f81273cb187bbad5a205ba883/Android/app/src/main/java/unibo/cvlab/pydnet/StreamActivity.java#L62
