### ISSUE TITLE
supported resolutions

### ISSUE THREAD

**Issue by elfifo4** [FilippoAleotti/mobilePydnet#7]
Hi @FilippoAleotti
I see in Resolution Enum (Android) these values: 
 RES1(512, 256), RES2(640, 192), RES3(320, 96), RES4(640, 448);
Are they only supported by the model?
I've tried to feed the model with a static image and it gets cropped.
thanks

**Comment by FilippoAleotti** [comment]
Hi,
In the code we define 4 enum resolutions, representing most used in our scenarios. About our model, it can handle images with height and width multiples of 64, and for this reason the image is resized before feeding the network.

**Comment by elfifo4** [comment]
Hi, is it possible to train the model on images with height and width multiples of 8?

**Comment by FilippoAleotti** [comment]
Using the provided network no, you have to change the architecture
